/*
=================== Surface Attributes Interpeted Language ===================
              |
    File:     | csg.c
    Version:  | 2.0 SAIL, 2.0 SAILER
              |
    Date:     | 20 Jul 1993
    Author:   | David Fletcher
              |
    Edit date:|
    Editor:   |
              |
    Summery:  | csg related routines
              |
              |
==============================================================================
*/

/* includes go here */

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "structs.h"
#include "mathfun.h"
#include "init.h"
#include "mathtype.h"
#include "sailpub.h"
#include "tokens.h"
#include "parse_tr.h"
#include "sail.h"
#include "support.h"

void sect_CSG(prim_type *,ray_type *);

static name_token_type values[] =
{
    {"operation",1},{"left",2},{"right",3},{"surface",4},
    {"UNION",10},{"INTERSECTION",10},{"DIFFERENCE",10},{"",-1}
};



#define IN 0
#define OUT 1

#define NONE 0x0
#define RIGHT 0x1
#define LEFT 0x2
#define BOTH 0x3

#define FALSE   0
#define TRUE    1

#define MAXINTERLEN 40
/* per-thread scratch: each render thread builds CSG intersection runs here */
static __thread struct data interT[MAXINTERLEN];
static __thread int curinter=0;

/* generated by mktbl.c */
static char table[256] =
{
    0,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,
    0,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,
    0,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,
    0,1,1,1,0,0,1,1,0,1,0,1,0,1,1,1,

    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,

    0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,
    0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,
    0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,
    0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,

    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};

#define BNN -1000000.0



/*
===============================================================
   Function:sect_CSG()
===============================================================
*/
void sect_CSG(prim_type *p,ray_type *ray)
{
CSG_type *CSG;
inter_type *cl;
inter_type *cr;
inter_type *cc;
double inR,inL,outR,outL;
interD_type *newData;  /* the current data */
interD_type *oldData;  /* the current data */
interD_type dummyold;
int optype;
int cur;
int newin,newout;
int usedL,usedR;
int tusedL,tusedR;
int currentRun = 0x0;
int firstrun=1;
int hit = 0x0;
int phit = 0x0; /* positive hit point ? */
char op;


    CSG = &p->prim.CSG;
    op = CSG->op;
    p->hit = 0x0;

    (*(CSG->left->sec_func)) (CSG->left,ray);
    if ((CSG->op == '-' || CSG->op == '*') && !CSG->left->hit) return;
    (*(CSG->right->sec_func)) (CSG->right,ray);

    if (CSG->left->hit == 0)
        cl= NULL;
    else
        cl = &CSG->left->inter;

    if (CSG->right->hit == 0)
        cr = NULL;
    else
        cr = &CSG->right->inter;

    switch(CSG->op)
    {
        case '+':
            if (CSG->left->hit == NULL && CSG->right->hit == NULL)
                return;
        break;
        case '*':
            if (!(CSG->left->hit && CSG->right->hit))
                return;
        break;
        case '-':
            if (!CSG->left->hit)
                return;
        break;
    }

    cc = &p->inter;

    dummyold.u = BNN; /* some big negative number */
    oldData = &dummyold;

    cc->next = NULL;

    switch(op)
    {
        case '+':   optype = 0; break;
        case '*':   optype = 0x40; break;
        case '-':   optype = 0x80; break;
    }

    tusedL = tusedR = OUT;
    usedL = usedR = OUT;

    while (cr != NULL || cl != NULL)
    {

        newin = 0x0;
        newout = 0x0;
        inR = inL = outR = outL = BNN;
        if (cr != NULL)
        {
            inR = cr->data[IN].u;
            outR = cr->data[OUT].u;
        }

        if (cl != NULL)
        {
            inL = cl->data[IN].u;
            outL = cl->data[OUT].u;
        }

        if (inR != BNN && inR > oldData->u &&
            (inR <= inL || inL == BNN || usedL == IN)  &&
            (inR <= outL || outL == BNN))
        {
            newData = &cr->data[IN];
            tusedR = IN;
            newin = RIGHT;
        } else if (outR != BNN && outR > oldData->u &&
            (outR <= outL || outL == BNN || usedL == OUT ) &&
            (outR <= inL || inL == BNN || usedL == IN))
        {
            newData = &cr->data[OUT];
            newout = RIGHT;
            tusedR = OUT;
        }

        if (inL != BNN && inL > oldData->u &&
            (inL <= inR || inR == BNN || usedR == IN) &&
            (inL <= outR || outR == BNN))
        {
            newData = &cl->data[IN];
            tusedL = IN;
            newin |= LEFT;
        }
        else if (outL != BNN && outL > oldData->u &&
            (outL <= outR || outR == BNN || usedR == OUT) &&
            (outL <= inR || inR == BNN || usedR == IN))
        {
            newData = &cl->data[OUT];
            newout |= LEFT;
            tusedL = OUT;
        }

        usedR = tusedR;
        usedL = tusedL;

        cur = newin | newout;

        /* now that we got the next point determine if we have a valid range */

        if (cur != BOTH)
        {
            if (cur & RIGHT && cl != NULL &&
                 newData->u > cl->data[IN].u && newData->u < cl->data[OUT].u)
                cur |= LEFT;
            else if (cur & LEFT && cr != NULL &&
            newData->u > cr->data[IN].u && newData->u < cr->data[OUT].u)
            cur |= RIGHT;
        }

        if (newout & RIGHT) cr = cr->next;
        if (newout & LEFT) cl = cl->next;

        if (table[optype | newin << 4 | newout << 2 | cur])
        {
            /* a valid range */
            if (!currentRun)
            {
                /*  new run. */
                if (firstrun)
                {
                    firstrun = FALSE;
                }
                else
                {
                    cc->next = &interT[curinter];
                    curinter = (curinter+1) % MAXINTERLEN;
                    cc = cc->next;
                    cc->next = NULL;
                }
                cc->data[IN] = *newData;   /* the new IN data values */
                if (cc->data[IN].u > 0.0001) phit=0x1;
                currentRun = TRUE;
            }
            else if (currentRun && cr == NULL && cl == NULL)
            {
                cc->data[OUT] = *newData;
                if (cc->data[OUT].u > 0.0001) phit=0x1;
                hit = TRUE;
            }
        }
        else
        {
            if (currentRun)
            {
                /* The end of a run. This is an OUT of a run.  */
                cc->data[OUT] = *newData;    /* then new OUT data values */
                if (cc->data[OUT].u > 0.0001) phit=0x1;
                currentRun = FALSE;
                hit = TRUE;
            }
        }
        oldData = newData;
    }
    if (!phit) hit = -hit;
    p->hit = hit;
}

/*
======================================
    BuildCSG()
======================================
*/
void *BuildCSG(assmt_type *AssmtList)
{
assmt_type *t;
int token;
sail_module_type *module;
char oper='+';
prim_type *left=NULL,*right=NULL;
struct sail_module_struct *surfacemodule=NULL;
prim_type *prim;

    module = (sail_module_type *) calloc(sizeof(sail_module_type),1);

    for (t = AssmtList; t != NULL; t = t->next)
    {
        switch(token = GetToken(t->lvalue,values))
        {
            case 1: /* operation */
                if (CheckValue(t,EXPRLST,CHARPTR,"CSG, operation"))
                {
                    oper = t->rvalue.data.ExprLst->u.CharPtrVal[0];
                }
            break;
            case 2: /* left */
                if (t->rvalue.Type == MODULE)
                {
                    left = (void *)t->rvalue.data.Module;
                }
                else if (CheckValue(t,EXPRLST,CHARPTR,"CSG, left"))
                {
                    left = (void *)
                        InitTexture(t->rvalue.data.ExprLst->u.CharPtrVal);
                }
            break;
            case 3: /* right */
                if (t->rvalue.Type == MODULE)
                {
                    right = (void *)t->rvalue.data.Module;
                }
                else if (CheckValue(t,EXPRLST,CHARPTR,"CSG, right"))
                {
                    right = (void *)
                        InitTexture(t->rvalue.data.ExprLst->u.CharPtrVal);
                }
            break;
            case 4: /* surface */
                if (t->rvalue.Type == MODULE)
                {
                    surfacemodule = t->rvalue.data.Module;
                }
                else if (CheckValue(t,EXPRLST,CHARPTR,"sphere, surface"))
                {
                    surfacemodule =
                        InitTexture(t->rvalue.data.ExprLst->u.CharPtrVal);
                }
            break;
            default:
                printf("Unknown lvalue (%s) found in a CSG module\n",t->lvalue);
                SAIL_ERROR_FLAG = TRUE;
            break;
        }
    }

    if (left==NULL) UnassignedErr("left in module CSG");
    if (right==NULL) UnassignedErr("right in module CSG");

    /* allocate a node */
    prim = AllocSectObject();
    prim->inter.next = NULL;
    prim->sec_func = sect_CSG;
    prim->inter.data[0].SurfAttrib = surfacemodule;
    prim->inter.data[1].SurfAttrib = surfacemodule;
    prim->prim.CSG.op = oper;
    prim->prim.CSG.left = left;
    prim->prim.CSG.right = right;
    prim->inter.data[0].nor_func = NULL;
    prim->inter.data[1].nor_func = NULL;
    left->isInCSG = 0x1;
    right->isInCSG = 0x1;

/* add these SOON (well not so soon (07 Aug 1993))*/
    prim->bound_func = NULL;
    return((void *)prim);
}
